apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresha.name" . }}-postgres-passwd
  labels:
    {{- include "postgresha.labels" . | nindent 4 }}
data:
  password: {{ default "" .Values.passwords.postgres | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresha.name" . }}-repuser-passwd
  labels:
    {{- include "postgresha.labels" . | nindent 4 }}
data:
  password: {{ default "" .Values.passwords.repuser | b64enc | quote }}