apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresha.name" . }}
  labels:
    {{- include "postgresha.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    {{- include "postgresha.selectorLabels" . | nindent 4 }}
